name: Github Pages Deploy Action
# You may pin to the exact commit or the version.
# uses: avinal/github-pages-deploy-action@7702e2ad1f82097323b08b428c8f57cb21dd965b
uses: avinal/github-pages-deploy-action@v0.9
  with:
    # GitHub access token with Repo Access
    GITHUB_TOKEN: # default is ${{ github.token }}
    # java(for JavaDoc), python(For Python Site/Documentation Generators)
    LANGUAGE: java
    # make command to generate html
    MAKE_COMMAND: # default is make html
    # Deploy pages to which branch
    PAGES_BRANCH: # default is gh-pages
    # Generate Site from which branch
    BUILD_FROM: # default is master
    # folder in which generated files are stored
    DOCS_FOLDER: # default is docs
